### ISSUE TITLE
Issues when using Temporary Containers

### ISSUE THREAD

**Issue by somoso** [Kouassi-Goli/contain-microsoft#2]
If you have Temporary Containers installed and set up to "Automatic Mode" (i.e. open every tab in a new temporary container) and then open a Microsoft website (e.g. onedrive.com), it will continuously flip between the temp container and the Microsoft container and will never actually load the website at all.

**Comment by aleksejrs** [comment]
Confirmed: it doesn't allow github.io to be opened in the Microsoft container.

**Comment by patrick-goli** [comment]
I couldn't reproduce the error.
I updated the domain list, it now supports Github.
