### ISSUE TITLE
Update domains

### ISSUE THREAD

**Issue by andyroutt** [Kouassi-Goli/contain-microsoft#3]
Please add `windowsazure.com` to `MICROSOFT_DOMAINS` for O365 authentication. Thanks

**Comment by Extarys** [comment]
Should also add github and npmjs.org to the list.

**Comment by Eragonfr** [comment]
Github is in the git container extension, if it's added to this one it's going to create a conflict.  
But i'd like to see `*.azure.com` in this extension.

**Comment by patrick-goli** [comment]
Feel free to put contribute with the list of Microsoft owned domains.

**Comment by patrick-goli** [comment]
> Github is in the git container extension, if it's added to this one it's going to create a conflict.

I will add a disclaimer for users of the git container extension
